---
- hosts: all # salt.camosun.ca
  become: true
  tasks:
    - name: Initialize some Apt packages
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
          ]
        state: present
        update_cache: yes

    - name: Add SaltStack GPG key
      apt_key:
        url: https://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub

    - name: Add SaltStack Apt Repo
      apt_repository:
        repo: deb http://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest focal main

    - name: Install list of Apt Packages
      apt:
        name: ["salt-master", "python3-pip", "python3-pygit2"]
        #"salt-minion",
        #"salt-ssh",
        #"salt-api"
        state: present
        update_cache: yes
        #
        #- name: Accept Master Minion Key
        #shell: |
        #if [[ $(salt-key -l unaccepted | grep $(hostname)) ]];
        #then salt-key -l unaccepted | grep $(hostname) | xargs salt-key -y -a ;
        #else salt-key -l accepted | grep $(hostname) | xargs salt-key -f | tail -n 1 ;
        #fi
        #args:
        #executable: /usr/bin/bash
